import type {
  CollectionJob,
  ContentItem,
  DashboardSnapshot,
  Source,
} from "./types";

const now = Date.now();
const ago = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const demoSources: Source[] = [
  {
    id: "src-x-ai",
    name: "X · AI 最新讨论",
    platform: "x",
    kind: "keyword",
    target: '(AI OR LLM OR "large language model") lang:en',
    intervalMinutes: 15,
    enabled: true,
    status: "healthy",
    lastSyncedAt: ago(4),
    itemCount: 186,
  },
  {
    id: "src-x-codex",
    name: "X · Codex / Agent",
    platform: "x",
    kind: "keyword",
    target: "(Codex OR AI agent OR coding agent)",
    intervalMinutes: 15,
    enabled: true,
    status: "healthy",
    lastSyncedAt: ago(7),
    itemCount: 94,
  },
  {
    id: "src-yt-ai",
    name: "YouTube · AI 频道雷达",
    platform: "youtube",
    kind: "keyword",
    target: "AI model Codex agent",
    intervalMinutes: 30,
    enabled: true,
    status: "healthy",
    lastSyncedAt: ago(12),
    itemCount: 72,
  },
  {
    id: "src-linuxdo-latest",
    name: "Linux.do · 最新话题",
    platform: "linuxdo",
    kind: "feed",
    target: "https://linux.do/latest.rss",
    intervalMinutes: 10,
    enabled: true,
    status: "healthy",
    lastSyncedAt: ago(2),
    itemCount: 241,
  },
  {
    id: "src-linuxdo-top",
    name: "Linux.do · 每日热门",
    platform: "linuxdo",
    kind: "feed",
    target: "https://linux.do/top.rss?period=daily",
    intervalMinutes: 15,
    enabled: true,
    status: "warning",
    lastSyncedAt: ago(28),
    itemCount: 48,
  },
  {
    id: "src-idcflare-daily-top",
    name: "IDCFlare · 每日热门",
    platform: "idcflare",
    kind: "feed",
    target: "https://idcflare.com/top.rss?period=daily",
    intervalMinutes: 15,
    enabled: true,
    status: "healthy",
    lastSyncedAt: null,
    itemCount: 0,
    config: {
      maxItems: 50,
      filterKeywords:
        "AI,大模型,LLM,OpenAI,Claude,GPT,Codex,Agent,VPS,服务器,主机,IP,CDN,域名,线路,U币,USDT,开卡,虚拟卡,支付",
      minValueScore: 42,
    },
  },
  {
    id: "src-gitlab-blog",
    name: "GitLab · 官方博客",
    platform: "gitlab",
    kind: "feed",
    target: "https://about.gitlab.com/atom.xml",
    intervalMinutes: 30,
    enabled: true,
    status: "healthy",
    lastSyncedAt: null,
    itemCount: 0,
    config: {
      maxItems: 50,
      filterKeywords:
        "AI,artificial intelligence,Duo,Agent,agentic,LLM,Claude,GPT,Codex,Cursor,MCP,DevSecOps,CI/CD,security,vulnerability,CVE,supply chain,container,Kubernetes,Runner",
      minValueScore: 45,
    },
  },
  {
    id: "src-gitlab-releases",
    name: "GitLab · 正式版本",
    platform: "gitlab",
    kind: "feed",
    target: "https://docs.gitlab.com/releases/releases.xml",
    intervalMinutes: 60,
    enabled: true,
    status: "healthy",
    lastSyncedAt: null,
    itemCount: 0,
    config: {
      maxItems: 20,
      filterKeywords: "",
      minValueScore: 45,
    },
  },
  {
    id: "src-gitlab-patches",
    name: "GitLab · 安全补丁",
    platform: "gitlab",
    kind: "feed",
    target: "https://docs.gitlab.com/releases/patch-releases.xml",
    intervalMinutes: 30,
    enabled: true,
    status: "healthy",
    lastSyncedAt: null,
    itemCount: 0,
    config: {
      maxItems: 30,
      filterKeywords: "",
      minValueScore: 45,
    },
  },
];

export const demoItems: ContentItem[] = [
  {
    id: "demo-1",
    externalId: "demo-x-codex-1",
    platform: "x",
    sourceId: "src-x-codex",
    type: "post",
    title: "Codex 工具链更新引发开发者对多代理工作流的新讨论",
    body: "开发者集中讨论更长任务、工具调用稳定性和代码审查闭环，关注点从单次生成转向持续执行与验证。",
    url: "https://x.com/",
    authorName: "AI Builder Watch",
    authorHandle: "@builderwatch",
    publishedAt: ago(18),
    fetchedAt: ago(4),
    metrics: { views: 128_400, likes: 2_940, replies: 186, reposts: 512 },
    hotScore: 92,
    tags: ["Codex", "Agent", "开发工具"],
    aiSummary:
      "讨论重点是编码代理从“生成代码”升级为“执行—验证—修复”的长链路工作方式；团队最关心权限控制、可观测性和失败恢复。",
    summaryStatus: "ready",
    topicId: "topic-codex",
  },
  {
    id: "demo-2",
    externalId: "demo-linuxdo-vps-1",
    platform: "linuxdo",
    sourceId: "src-linuxdo-top",
    type: "topic",
    title: "洛杉矶 VPS 线路与 AI API 稳定性经验汇总",
    body: "社区围绕延迟、线路质量、出口风控和长期成本展开讨论，并分享了多种监控方式。",
    url: "https://linux.do/",
    authorName: "Linux.do 社区",
    publishedAt: ago(42),
    fetchedAt: ago(28),
    metrics: { views: 8_920, likes: 138, replies: 96 },
    hotScore: 88,
    tags: ["VPS", "洛杉矶", "网络"],
    aiSummary:
      "选型不能只看带宽价格，应同时验证晚高峰丢包、目标 API 出口信誉和故障迁移能力；适合作为部署前的线路测试清单。",
    summaryStatus: "ready",
    topicId: "topic-vps",
  },
  {
    id: "demo-3",
    externalId: "demo-yt-model-1",
    platform: "youtube",
    sourceId: "src-yt-ai",
    type: "video",
    title: "一周大模型进展：推理、上下文与 Agent 评测正在发生什么",
    body: "视频梳理近期模型更新，比较推理能力、工具使用和长上下文表现，并讨论评测数据的局限。",
    url: "https://www.youtube.com/",
    authorName: "Model Signal",
    authorHandle: "@modelsignal",
    publishedAt: ago(66),
    fetchedAt: ago(12),
    metrics: { views: 76_300, likes: 4_210, comments: 384 },
    hotScore: 84,
    tags: ["大模型", "评测", "Agent"],
    aiSummary:
      "近期变化不只是榜单分数提升，更重要的是工具调用稳定性和复杂任务完成率；建议把官方评测与真实工作流测试结合。",
    summaryStatus: "ready",
    topicId: "topic-models",
  },
  {
    id: "demo-4",
    externalId: "demo-linuxdo-pay-1",
    platform: "linuxdo",
    sourceId: "src-linuxdo-latest",
    type: "topic",
    title: "海外订阅、虚拟卡与 U 币支付风险清单",
    body: "用户分享支付渠道变化、费率和风控经历，讨论如何减少余额、账号和合规风险。",
    url: "https://linux.do/",
    authorName: "Linux.do 社区",
    publishedAt: ago(91),
    fetchedAt: ago(2),
    metrics: { views: 5_680, likes: 82, replies: 71 },
    hotScore: 79,
    tags: ["开卡", "U币", "订阅"],
    aiSummary:
      "高频风险集中在渠道突然失效、身份信息不一致和资金不可逆；应小额测试、控制余额，并避免依赖单一支付路径。",
    summaryStatus: "ready",
    topicId: "topic-payment",
  },
  {
    id: "demo-5",
    externalId: "demo-x-open-model-1",
    platform: "x",
    sourceId: "src-x-ai",
    type: "post",
    title: "开源模型社区把注意力转向更小、更快的部署方案",
    body: "讨论集中在量化、推理吞吐、显存占用以及边缘设备部署，多个项目展示了新的性能优化结果。",
    url: "https://x.com/",
    authorName: "Open Model Radar",
    authorHandle: "@openmodelradar",
    publishedAt: ago(133),
    fetchedAt: ago(7),
    metrics: { views: 92_100, likes: 1_720, replies: 104, reposts: 338 },
    hotScore: 75,
    tags: ["开源模型", "推理", "部署"],
    aiSummary:
      "社区热点正从参数规模转向单位成本产出；对内部应用而言，吞吐、显存和可维护性可能比极限榜单成绩更重要。",
    summaryStatus: "ready",
    topicId: "topic-models",
  },
  {
    id: "demo-6",
    externalId: "demo-yt-agent-1",
    platform: "youtube",
    sourceId: "src-yt-ai",
    type: "video",
    title: "从零搭建可观测的 AI Agent：队列、重试与成本控制",
    body: "演示如何把长任务拆分为可恢复步骤，并记录模型调用、工具结果和失败原因。",
    url: "https://www.youtube.com/",
    authorName: "Practical Agents",
    authorHandle: "@practicalagents",
    publishedAt: ago(188),
    fetchedAt: ago(12),
    metrics: { views: 31_900, likes: 1_890, comments: 226 },
    hotScore: 71,
    tags: ["Agent", "工程化", "成本"],
    aiSummary:
      "核心不是更复杂的 Prompt，而是把任务状态、幂等、重试和预算做成系统能力；这与本平台的采集 Worker 设计一致。",
    summaryStatus: "ready",
    topicId: "topic-codex",
  },
];

export const demoJobs: CollectionJob[] = [
  {
    id: "job-1",
    sourceId: "src-linuxdo-latest",
    sourceName: "Linux.do · 最新话题",
    platform: "linuxdo",
    status: "succeeded",
    itemsFound: 30,
    itemsAdded: 11,
    durationMs: 842,
    startedAt: ago(3),
    completedAt: ago(2),
  },
  {
    id: "job-2",
    sourceId: "src-x-ai",
    sourceName: "X · AI 最新讨论",
    platform: "x",
    status: "succeeded",
    itemsFound: 20,
    itemsAdded: 7,
    durationMs: 1_486,
    startedAt: ago(5),
    completedAt: ago(4),
  },
  {
    id: "job-3",
    sourceId: "src-yt-ai",
    sourceName: "YouTube · AI 频道雷达",
    platform: "youtube",
    status: "running",
    itemsFound: 0,
    itemsAdded: 0,
    durationMs: null,
    startedAt: ago(1),
    completedAt: null,
  },
  {
    id: "job-4",
    sourceId: "src-linuxdo-top",
    sourceName: "Linux.do · 每日热门",
    platform: "linuxdo",
    status: "failed",
    itemsFound: 0,
    itemsAdded: 0,
    durationMs: 1_202,
    errorMessage: "RSS 暂时返回 403，已进入退避等待",
    startedAt: ago(29),
    completedAt: ago(28),
  },
];

export const demoDashboard: DashboardSnapshot = {
  mode: "demo",
  generatedAt: new Date(now).toISOString(),
  stats: {
    contents24h: 348,
    hotTopics: 0,
    activeSources: 9,
    successRate: 96.8,
    apiRequestsToday: 426,
    estimatedCostUsd: 0.43,
  },
  platformCounts: {
    x: 184,
    youtube: 67,
    linuxdo: 97,
    idcflare: 0,
    gitlab: 0,
  },
  hotTopics: [],
  latestItems: demoItems,
  sources: demoSources,
  jobs: demoJobs,
};
